create table if not exists tipo_estabelecimento (
    id_tipo_estabelecimento bigint generated by default as identity primary key,
    codigo varchar(40) not null,
    descricao varchar(100),
    ativo boolean not null default true
);

create table if not exists tipo_cobranca (
    id_tipo_cobranca bigint generated by default as identity primary key,
    codigo varchar(30) not null,
    descricao varchar(100),
    ativo boolean not null default true
);

create table if not exists tipo_desconto (
    id_tipo_desconto bigint generated by default as identity primary key,
    codigo varchar(30) not null,
    descricao varchar(100),
    ativo boolean not null default true
);

create table if not exists tipo_aplicacao_desconto (
    id_tipo_aplicacao_desconto bigint generated by default as identity primary key,
    codigo varchar(30) not null,
    descricao varchar(150),
    ativo boolean not null default true
);

create table if not exists condicao_desconto (
    id_condicao_desconto bigint generated by default as identity primary key,
    codigo varchar(50) not null,
    descricao varchar(150),
    ativo boolean not null default true
);

create table if not exists forma_pagamento (
    id_forma_pagamento bigint generated by default as identity primary key,
    codigo varchar(40) not null,
    descricao varchar(100),
    permite_recorrencia boolean not null default false,
    ativo boolean not null default true
);

create table if not exists role_estabelecimento (
    id_role_estabelecimento bigint generated by default as identity primary key,
    codigo varchar(40) not null,
    descricao varchar(100),
    ativo boolean not null default true
);

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'uk_tipo_estabelecimento_codigo') then
        alter table tipo_estabelecimento add constraint uk_tipo_estabelecimento_codigo unique (codigo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'uk_tipo_cobranca_codigo') then
        alter table tipo_cobranca add constraint uk_tipo_cobranca_codigo unique (codigo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'uk_tipo_desconto_codigo') then
        alter table tipo_desconto add constraint uk_tipo_desconto_codigo unique (codigo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'uk_tipo_aplicacao_desconto_codigo') then
        alter table tipo_aplicacao_desconto add constraint uk_tipo_aplicacao_desconto_codigo unique (codigo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'uk_condicao_desconto_codigo') then
        alter table condicao_desconto add constraint uk_condicao_desconto_codigo unique (codigo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'uk_forma_pagamento_codigo') then
        alter table forma_pagamento add constraint uk_forma_pagamento_codigo unique (codigo);
    end if;

    if not exists (select 1 from pg_constraint where conname = 'uk_role_estabelecimento_codigo') then
        alter table role_estabelecimento add constraint uk_role_estabelecimento_codigo unique (codigo);
    end if;
end $$;

insert into tipo_estabelecimento (codigo, descricao, ativo) values
    ('ACADEMIA', 'Academia', true),
    ('STUDIO', 'Studio', true),
    ('BOX', 'Box', true),
    ('CENTRO_ESPORTIVO', 'Centro esportivo', true),
    ('ARTES_MARCIAIS', 'Artes marciais', true),
    ('OUTRO', 'Outro', true)
on conflict (codigo) do update set
    descricao = excluded.descricao,
    ativo = excluded.ativo;

insert into tipo_cobranca (codigo, descricao, ativo) values
    ('MENSAL', 'Mensal', true),
    ('RECORRENTE', 'Recorrente', true),
    ('UNICO', 'Unico', true)
on conflict (codigo) do update set
    descricao = excluded.descricao,
    ativo = excluded.ativo;

insert into tipo_desconto (codigo, descricao, ativo) values
    ('PERCENTUAL', 'Percentual', true),
    ('VALOR_FIXO', 'Valor fixo', true)
on conflict (codigo) do update set
    descricao = excluded.descricao,
    ativo = excluded.ativo;

insert into tipo_aplicacao_desconto (codigo, descricao, ativo) values
    ('UNICO', 'Aplicado uma unica vez', true),
    ('POR_PERIODO', 'Aplicado durante determinada quantidade de meses', true),
    ('RECORRENTE', 'Aplicado continuamente enquanto permanecer valido', true)
on conflict (codigo) do update set
    descricao = excluded.descricao,
    ativo = excluded.ativo;

insert into condicao_desconto (codigo, descricao, ativo) values
    ('CARTAO_CADASTRADO', 'Cartao cadastrado', true),
    ('CONVENIO_EMPRESA', 'Convenio com empresa', true),
    ('PRIMEIRA_MATRICULA', 'Primeira matricula', true),
    ('PAGAMENTO_ANTECIPADO', 'Pagamento antecipado', true),
    ('INDICACAO', 'Indicacao', true)
on conflict (codigo) do update set
    descricao = excluded.descricao,
    ativo = excluded.ativo;

insert into forma_pagamento (codigo, descricao, permite_recorrencia, ativo) values
    ('PIX', 'Pix', false, true),
    ('DINHEIRO', 'Dinheiro', false, true),
    ('CARTAO_CREDITO', 'Cartao de credito', true, true),
    ('CARTAO_DEBITO', 'Cartao de debito', false, true),
    ('BOLETO', 'Boleto', false, true),
    ('TRANSFERENCIA', 'Transferencia', false, true)
on conflict (codigo) do update set
    descricao = excluded.descricao,
    permite_recorrencia = excluded.permite_recorrencia,
    ativo = excluded.ativo;

insert into role_estabelecimento (codigo, descricao, ativo) values
    ('ADMIN_ESTABELECIMENTO', 'Administrador do estabelecimento', true),
    ('RECEPCIONISTA', 'Recepcionista', true)
on conflict (codigo) do update set
    descricao = excluded.descricao,
    ativo = excluded.ativo;
